export const APP_IMAGE = {
  owner: '/assets/images/owner.webp',
  farm: '/assets/images/farms-crops.webp',
  factory: '/assets/images/factory.webp',
  logo: '/assets/images/logo.webp',
  whatsappSVG: '/assets/svgs/whatsapp.svg',
  facebookSVG: '/assets/svgs/facebook.svg',
  indiaSVG: '/assets/svgs/india.svg',
  instagramSVG: '/assets/svgs/instagram.svg',
  instagramWhiteSVG: '/assets/svgs/instagram-white.svg',
  ukSVG: '/assets/svgs/uk.svg',
  products: {
    chia: '/assets/products/chiaseeds.webp',
    maize771: '/assets/products/hybridmaize-771.webp',
    maize775: '/assets/products/hybridmaize-775.webp',
    jwala07: '/assets/products/jwala07.webp',
    jwala13: '/assets/products/jwala13.webp',
    pdm139: '/assets/products/moongseeds-pdm139.webp',
    s444: '/assets/products/moongseeds-s444.webp',
    talvar: '/assets/products/moongseedsdoubletalvar.webp',
    hum12: '/assets/products/moongseedshum12.webp',
    jhumki: '/assets/products/moongseedsjhumki.webp',
    megha: '/assets/products/moongseedsmegha.webp',
    virat: '/assets/products/moongseedsshikhaipm410.webp',
    mustard: '/assets/products/mustardseeds.webp',
    mustard3536: '/assets/products/mustardseeds3536.webp',
    sanskritipdm139: '/assets/products/sanskritimoongseeds-pdm139.webp',
  },
};
